### ISSUE TITLE
Standby current

### ISSUE THREAD

**Issue by perigoso** [raplin/DPS-1200FB#5]
I don't own one of these supplies so i can't test it, but in this documentation you state a high standby current of possibly 1+ A, but that sounds way too high, that would mean it wastes 12W in standby. could you get the input power in standby?

**Comment by vochong** [comment]
I actually measured the power consumption when only the standby 12V is available.  It's about 11.5 W doing nothing!   So yes it wastes about 12 W in standby mode.

**Comment by raplin** [comment]
Hey, it's only 1% of the maximum power rating ;-)
